// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMyqz7m0tjVTFVaGpLj11-Ijrv0vuSIJY',
    appId: '1:266668298887:web:ccee57ed053c2a5e8f1e22',
    messagingSenderId: '266668298887',
    projectId: 'reminder-app-dffaf',
    authDomain: 'reminder-app-dffaf.firebaseapp.com',
    storageBucket: 'reminder-app-dffaf.firebasestorage.app',
    measurementId: 'G-L945HMSLB2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCs_4Ls6DXiDbhlm29Q27Eur2HQixyJSs',
    appId: '1:266668298887:android:8ffabca1dc8638e18f1e22',
    messagingSenderId: '266668298887',
    projectId: 'reminder-app-dffaf',
    storageBucket: 'reminder-app-dffaf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5owiht1Aj62gS2jxBTAfp7hKcP-ZVyZQ',
    appId: '1:266668298887:ios:395e86fb82e61c178f1e22',
    messagingSenderId: '266668298887',
    projectId: 'reminder-app-dffaf',
    storageBucket: 'reminder-app-dffaf.firebasestorage.app',
    iosBundleId: 'com.example.notification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5owiht1Aj62gS2jxBTAfp7hKcP-ZVyZQ',
    appId: '1:266668298887:ios:395e86fb82e61c178f1e22',
    messagingSenderId: '266668298887',
    projectId: 'reminder-app-dffaf',
    storageBucket: 'reminder-app-dffaf.firebasestorage.app',
    iosBundleId: 'com.example.notification',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMyqz7m0tjVTFVaGpLj11-Ijrv0vuSIJY',
    appId: '1:266668298887:web:2e4d352f1515fd498f1e22',
    messagingSenderId: '266668298887',
    projectId: 'reminder-app-dffaf',
    authDomain: 'reminder-app-dffaf.firebaseapp.com',
    storageBucket: 'reminder-app-dffaf.firebasestorage.app',
    measurementId: 'G-XL3QCFFV76',
  );
}
